#!/usr/sbin/nft -f

flush ruleset

table inet metis_egress {
    chain output {
        type filter hook output priority 0; policy accept;
        meta skuid 65532 ct state established,related accept
        meta skuid 65532 oifname "lo" accept
        meta skuid 65532 counter reject
    }
}
